version: '3.8'

services:
  chatbot-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chatbot-demo:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run demo_app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
    environment:
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    depends_on:
      - chatbot-api
    restart: unless-stopped

networks:
  default:
    name: skillhigh-chatbot-network
